In [1]:
import numpy as np

In [27]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object=list_)

In [18]:
type(array_list)

numpy.ndarray

In [19]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
"""
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans: yes there is difference in data type of these variable list_ and array_list.
"""

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

In [ ]:
"""
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
"""

In [10]:
for i in list_: 
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [12]:
# Q3. Considering the following changes in the variable, array_list:

In [33]:
array_list=np.array(object=list_, dtype=int)

In [34]:
array_list

array([1, 2, 3, 4, 5])

In [35]:
array_list.dtype

dtype('int64')

In [ ]:
"""
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans: Yes, there is differene in list_ and arra_list variable , is thet data storage format in list_ is string,
     where as in the arr_list storage formate is in integer.

In [31]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [36]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [37]:
# Consider the below code to answer further questions:

In [38]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [39]:
num_list=np.array(object=num_list)

In [40]:
num_list

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
num_list.shape

(2, 3)

In [42]:
num_list.size

6

In [44]:
xero=np.zeros((3,3))

In [45]:
xero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
ide=np.eye(5,5)

In [49]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])