In [10]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [10]:
b=np.matrix(l)  #by default matrix is two dimensional array.

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.array(b)


array([[1, 2, 3, 4]])

In [13]:
a=np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c=a  #solo copy if we make change in c than also get change in a.

In [16]:
c

array([1, 2, 3, 4])

In [17]:
c[0]=100

In [18]:
c


array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d=np.copy(a)  # to avoid the solo copy we are using copy() function.
               # D store data in new location.(deep copy)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
a[1]=400

In [24]:
a

array([100, 400,   3,   4])

In [25]:
d

array([100,   2,   3,   4])

In [26]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
iterable=(i*i for i in range(5))

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('12 123',sep=' ')  #seprate based on space.

array([ 12., 123.])

In [3]:
np.fromstring('12,123',sep=',')  #seprate based on comma.

array([ 12., 123.])

In [4]:
# data-type in numpy

In [5]:
l=[1,3,4,5]

In [6]:
arr=np.array(l)

In [7]:
arr

array([1, 3, 4, 5])

In [9]:
arr.ndim   # show the dimensions of array.


1

In [10]:
ar2=np.array([[1,2,3],[4,5,6]])

In [11]:
ar2.ndim

2

In [12]:
arr.size

4

In [14]:
ar2.size

6

In [18]:
arr

array([1, 3, 4, 5])

In [16]:
arr.shape # 4 columns

(4,)

In [19]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
ar2.shape

(2, 3)

In [21]:
arr.dtype

dtype('int64')

In [22]:
ar2.dtype

dtype('int64')

In [33]:
arr2=np.array([[1.1,2,3],[2,3,4]])

In [34]:
arr2

array([[1.1, 2. , 3. ],
       [2. , 3. , 4. ]])

In [36]:
arr2.dtype

dtype('float64')

In [37]:
list(range(1.2,5))

TypeError: 'float' object cannot be interpreted as an integer

In [44]:
np.arange(1.2,5.2, 0.5)

array([1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7])

In [45]:
list(np.arange(1.2,5.2, 0.5))

[1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7]

In [46]:
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [3]:
arr2=np.zeros((3,2,3,2))

In [4]:
arr2

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [5]:
arr2.ndim

4

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
on=np.ones((2,3,2))

In [11]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
on+2

array([[[3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.]]])

In [14]:
np.empty((3,2))

array([[4.69038245e-310, 0.00000000e+000],
       [2.14321575e-312, 8.48798317e-313],
       [8.70018275e-313, 0.00000000e+000]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.linspace(2,3,20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [21]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [22]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [24]:
arr5=np.random.rand(3,4)

In [25]:
arr5

array([[0.67800542, 0.90403901, 0.75383133, 0.22717461],
       [0.29720005, 0.64127225, 0.19685274, 0.0848273 ],
       [0.13082508, 0.13087876, 0.84594349, 0.70953411]])

In [9]:
import pandas as pd

In [27]:
pd.DataFrame(arr5)

0         1         2         3
0  0.678005  0.904039  0.753831  0.227175
1  0.297200  0.641272  0.196853  0.084827
2  0.130825  0.130879  0.845943  0.709534

In [28]:
np.random.randn(2,4)

array([[-1.03512526, -0.2092819 , -1.03049224, -3.44506234],
       [-1.5531002 , -1.26369972, -1.1722138 , -0.42824484]])

In [30]:
np.random.rand(3,4)

array([[0.22037576, 0.72046187, 0.76301448, 0.79118708],
       [0.62672953, 0.48820943, 0.27080697, 0.18562269],
       [0.49717704, 0.56630187, 0.088226  , 0.87063087]])

In [11]:
df3=np.random.randint(1,100, (30,12))

In [12]:
df3

array([[ 8, 14, 89, 33, 75, 63, 89, 31, 14, 95, 26, 61],
       [18, 87, 38, 56, 56, 43, 22, 11, 26, 75, 56, 94],
       [63, 17, 71, 91, 80, 56, 93, 92, 80, 32, 32, 59],
       [46,  4, 16,  4, 78, 74, 77, 18, 71, 75, 64, 14],
       [36,  1, 54, 96,  7, 99, 47, 54, 12, 19, 52, 10],
       [82, 39, 95, 38, 96, 22, 88, 92, 39, 45, 37, 15],
       [72, 23, 17, 49, 79, 47, 99, 28, 28, 16,  1, 98],
       [75, 87, 38,  5,  9, 13,  1, 19, 69, 85, 82, 23],
       [34,  8, 16, 22, 32, 35, 17, 57, 87,  4, 88, 75],
       [78, 87, 10, 12, 88, 48, 56, 87, 68, 47, 20,  5],
       [19, 45, 87, 95, 90, 75, 49, 29, 47, 86, 65, 98],
       [74, 75, 76, 33,  7, 31, 35, 41, 29, 95,  9, 51],
       [89, 24, 50, 30, 52, 19, 74, 24, 62, 54, 79,  2],
       [71, 66, 68, 95, 39, 47, 50, 14, 34, 48, 43, 42],
       [23, 20, 74, 21, 37, 42, 57,  5, 39, 29,  7, 42],
       [67, 71,  7, 23, 31, 32, 95, 13, 33, 53, 85, 66],
       [34, 68, 48, 67, 32, 41, 63, 63, 98, 32, 35, 15],
       [83, 47,  6, 45, 98, 38,

In [14]:
df2=pd.DataFrame(df3)

In [16]:
df2.to_csv('matrix.csv')

In [17]:
arr=np.random.rand(3,2)

In [18]:
arr

array([[0.02607148, 0.61384274],
       [0.53214149, 0.2700948 ],
       [0.1303232 , 0.80432919]])

In [28]:
arr1=arr.reshape(2,3)

In [20]:
arr.reshape(6)

array([0.02607148, 0.61384274, 0.53214149, 0.2700948 , 0.1303232 ,
       0.80432919])

In [22]:
arr1

array([[0.02607148, 0.61384274, 0.53214149],
       [0.2700948 , 0.1303232 , 0.80432919]])

In [24]:
arr1[1][2]

0.8043291919116294

In [29]:
arr2=np.random.rand(4,3)

In [30]:
arr2

array([[0.02707344, 0.63298582, 0.0544687 ],
       [0.01467886, 0.99975343, 0.11129444],
       [0.79145037, 0.60602212, 0.99827932],
       [0.17849715, 0.42793011, 0.98572546]])

In [35]:
arr2[1:4,(1,2)]

array([[0.99975343, 0.11129444],
       [0.60602212, 0.99827932],
       [0.42793011, 0.98572546]])

In [38]:
arr3=np.random.randint(1,100,(5,5))

In [39]:
arr3

array([[ 6, 51, 83, 37, 43],
       [ 1, 78, 81, 36, 30],
       [12, 74, 65, 15, 37],
       [49,  5,  3, 86, 53],
       [89, 10, 60, 34, 54]])

In [41]:
arr3[arr3>50]

array([51, 83, 78, 81, 74, 65, 86, 53, 89, 60, 54])

In [42]:
arr3


array([[ 6, 51, 83, 37, 43],
       [ 1, 78, 81, 36, 30],
       [12, 74, 65, 15, 37],
       [49,  5,  3, 86, 53],
       [89, 10, 60, 34, 54]])

In [43]:
arr3[0][0]

6

In [44]:
arr3[0][0]=300

In [45]:
arr3

array([[300,  51,  83,  37,  43],
       [  1,  78,  81,  36,  30],
       [ 12,  74,  65,  15,  37],
       [ 49,   5,   3,  86,  53],
       [ 89,  10,  60,  34,  54]])

In [46]:
arr4=np.random.randint(1,3,(2,2))
arr5=np.random.randint(1,3,(2,2))

In [47]:
arr4

array([[2, 2],
       [1, 2]])

In [48]:
arr5

array([[1, 2],
       [1, 2]])

In [49]:
arr4+arr5

array([[3, 4],
       [2, 4]])

In [50]:
arr4-arr5

array([[1, 0],
       [0, 0]])

In [51]:
arr4*arr5

array([[2, 4],
       [1, 4]])

In [52]:
arr4@arr5

array([[4, 8],
       [3, 6]])

In [53]:
arr4/0

/tmp/ipykernel_77/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf],
       [inf, inf]])

In [54]:
arr4+100

array([[102, 102],
       [101, 102]])

In [55]:
arr4**2

array([[4, 4],
       [1, 4]])

In [56]:
# numpy - brodcasting.

In [75]:
arr5=np.zeros((3,3))

In [76]:
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
row=np.array([1,2,3])

In [78]:
row

array([1, 2, 3])

In [79]:
arr5+row  # row wise brodcasting in whole matrix.

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [67]:
row1=np.array([[1,2,3]]) # for column wise brodcasting in matrix.

In [70]:
col=row1.T

In [71]:
col

array([[1],
       [2],
       [3]])

In [80]:
arr5+col    #column wise brodcasting in matrix.

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [83]:
arr6=np.random.randint(1,100, (3,4))

In [84]:
arr6

array([[ 8, 44, 94, 54],
       [65, 81, 23, 55],
       [36, 50, 87, 67]])

In [85]:
np.sqrt(arr6)

array([[2.82842712, 6.63324958, 9.69535971, 7.34846923],
       [8.06225775, 9.        , 4.79583152, 7.41619849],
       [6.        , 7.07106781, 9.32737905, 8.18535277]])

In [86]:
np.exp(arr6)

array([[2.98095799e+03, 1.28516001e+19, 6.66317622e+40, 2.83075330e+23],
       [1.69488924e+28, 1.50609731e+35, 9.74480345e+09, 7.69478527e+23],
       [4.31123155e+15, 5.18470553e+21, 6.07603023e+37, 1.25236317e+29]])

In [88]:
np.log2(arr6)

array([[3.        , 5.45943162, 6.55458885, 5.7548875 ],
       [6.02236781, 6.33985   , 4.52356196, 5.78135971],
       [5.169925  , 5.64385619, 6.4429435 , 6.06608919]])