In [1]:
#short, searching & counting function.

In [2]:
import numpy as np

In [5]:
arr=np.array([2,5,7,82,4,6,7,85,4])

In [6]:
arr

array([ 2,  5,  7, 82,  4,  6,  7, 85,  4])

In [8]:
np.sort(arr)

array([ 2,  4,  4,  5,  6,  7,  7, 82, 85])

In [9]:
np.searchsorted(arr, 23)

7

In [10]:
arr1=np.array([0,231,123,43,534,0,0,0])

In [11]:
arr1

array([  0, 231, 123,  43, 534,   0,   0,   0])

In [12]:
np.count_nonzero(arr1)

4

In [13]:
arr

array([ 2,  5,  7, 82,  4,  6,  7, 85,  4])

In [14]:
np.where(arr>6)

(array([2, 3, 6, 7]),)

In [16]:
np.extract(arr>6,arr)

array([ 7, 82,  7, 85])

In [17]:
arr

array([ 2,  5,  7, 82,  4,  6,  7, 85,  4])

In [18]:
arr.byteswap()

array([ 144115188075855872,  360287970189639680,  504403158265495552,
       5908722711110090752,  288230376151711744,  432345564227567616,
        504403158265495552, 6124895493223874560,  288230376151711744])

In [19]:
a=np.copy(arr) #deep copy.

In [20]:
a


array([ 2,  5,  7, 82,  4,  6,  7, 85,  4])

In [21]:
b=arr.view()  # this is same like solo copy.

In [22]:
b

array([ 2,  5,  7, 82,  4,  6,  7, 85,  4])

In [24]:
b[0]=43

In [25]:
arr

array([43,  5,  7, 82,  4,  6,  7, 85,  4])

In [26]:
b

array([43,  5,  7, 82,  4,  6,  7, 85,  4])

In [27]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
nm.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
#numpy - linear algerba.

In [35]:
arr1=np.random.randint([[3,4],[4,5]])

In [36]:
arr1

array([[2, 2],
       [2, 2]])

In [37]:
arr2=np.random.randint([[3,4],[4,5]])

In [38]:
arr2

array([[0, 2],
       [0, 1]])

In [39]:
arr1.dot(arr2)

array([[0, 6],
       [0, 6]])

In [40]:
arr1@arr2

array([[0, 6],
       [0, 6]])