In [1]:
# numpy - data manipulation


In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[7, 3, 3, 6],
       [7, 9, 1, 9],
       [7, 4, 2, 4]])

In [5]:
arr.reshape(6,2)

array([[7, 3],
       [3, 6],
       [7, 9],
       [1, 9],
       [7, 4],
       [2, 4]])

In [6]:
arr.reshape(4,3)

array([[7, 3, 3],
       [6, 7, 9],
       [1, 9, 7],
       [4, 2, 4]])

In [7]:
arr.reshape(4,-2)

array([[7, 3, 3],
       [6, 7, 9],
       [1, 9, 7],
       [4, 2, 4]])

In [8]:
arr.T

array([[7, 7, 7],
       [3, 9, 4],
       [3, 1, 2],
       [6, 9, 4]])

In [9]:
arr.flatten()   #simply convert in one dimesional array.

array([7, 3, 3, 6, 7, 9, 1, 9, 7, 4, 2, 4])

In [10]:
arr1=np.array([1,2,3,4])

In [12]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4]])

In [16]:
np.squeeze(arr)

array([[7, 3, 3, 6],
       [7, 9, 1, 9],
       [7, 4, 2, 4]])

In [17]:
data=np.array([[1],[2],[4]])

In [18]:
data

array([[1],
       [2],
       [4]])

In [19]:
np.squeeze(data)

array([1, 2, 4])

In [20]:
arr1

array([1, 2, 3, 4])

In [22]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [24]:
np.roll(arr1, shift=2)

array([3, 4, 1, 2])

In [25]:
arr1

array([1, 2, 3, 4])

In [26]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
# numpy - binary operation

In [28]:
arr2=np.random.randint(1,10,(3,4))

In [30]:
arr3=np.random.randint(1,10,(3,4))

In [31]:
arr2

array([[9, 3, 2, 7],
       [4, 2, 6, 7],
       [9, 2, 4, 6]])

In [32]:
arr3

array([[2, 3, 9, 9],
       [9, 1, 9, 7],
       [3, 7, 9, 4]])

In [33]:
arr2+arr3

array([[11,  6, 11, 16],
       [13,  3, 15, 14],
       [12,  9, 13, 10]])

In [34]:
arr2*arr3

array([[18,  9, 18, 63],
       [36,  2, 54, 49],
       [27, 14, 36, 24]])

In [35]:
arr2/arr3

array([[4.5       , 1.        , 0.22222222, 0.77777778],
       [0.44444444, 2.        , 0.66666667, 1.        ],
       [3.        , 0.28571429, 0.44444444, 1.5       ]])

In [36]:
arr1-arr2

array([[-8, -1,  1, -3],
       [-3,  0, -3, -3],
       [-8,  0, -1, -2]])

In [39]:
arr2%arr3

array([[1, 0, 2, 7],
       [4, 0, 6, 0],
       [0, 2, 4, 2]])

In [40]:
arr1**arr3

array([[     1,      8,  19683, 262144],
       [     1,      2,  19683,  16384],
       [     1,    128,  19683,    256]])

In [41]:
arr2 &arr3  #binary and operation

array([[0, 3, 0, 1],
       [0, 0, 0, 7],
       [1, 2, 0, 4]])

In [43]:
~arr2

array([[-10,  -4,  -3,  -8],
       [ -5,  -3,  -7,  -8],
       [-10,  -3,  -5,  -7]])

In [44]:
arr2|arr3

array([[11,  3, 11, 15],
       [13,  3, 15,  7],
       [11,  7, 13,  6]])

In [45]:
arr2>arr3

array([[ True, False, False, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [46]:
#numpy - string function

In [47]:
arr=np.array(['abishek', 'kumar'])

In [48]:
arr


array(['abishek', 'kumar'], dtype='<U7')

In [49]:
np.char.upper(arr)

array(['ABISHEK', 'KUMAR'], dtype='<U7')

In [50]:
np.char.title(arr)

array(['Abishek', 'Kumar'], dtype='<U7')

In [51]:
np.char.capitalize(arr)

array(['Abishek', 'Kumar'], dtype='<U7')

In [52]:
#numpy mathmarical function.

In [56]:
arr3

array([[2, 3, 9, 9],
       [9, 1, 9, 7],
       [3, 7, 9, 4]])

In [57]:
np.sin(arr3)

array([[ 0.90929743,  0.14112001,  0.41211849,  0.41211849],
       [ 0.41211849,  0.84147098,  0.41211849,  0.6569866 ],
       [ 0.14112001,  0.6569866 ,  0.41211849, -0.7568025 ]])

In [58]:
np.cos(arr3)

array([[-0.41614684, -0.9899925 , -0.91113026, -0.91113026],
       [-0.91113026,  0.54030231, -0.91113026,  0.75390225],
       [-0.9899925 ,  0.75390225, -0.91113026, -0.65364362]])

In [59]:
np.tan(arr3)

array([[-2.18503986, -0.14254654, -0.45231566, -0.45231566],
       [-0.45231566,  1.55740772, -0.45231566,  0.87144798],
       [-0.14254654,  0.87144798, -0.45231566,  1.15782128]])

In [60]:
np.log10(arr3)

array([[0.30103   , 0.47712125, 0.95424251, 0.95424251],
       [0.95424251, 0.        , 0.95424251, 0.84509804],
       [0.47712125, 0.84509804, 0.95424251, 0.60205999]])

In [61]:
np.exp(arr3)

array([[7.38905610e+00, 2.00855369e+01, 8.10308393e+03, 8.10308393e+03],
       [8.10308393e+03, 2.71828183e+00, 8.10308393e+03, 1.09663316e+03],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03, 5.45981500e+01]])

In [62]:
np.power(arr3,2)

array([[ 4,  9, 81, 81],
       [81,  1, 81, 49],
       [ 9, 49, 81, 16]])

In [63]:
arr3

array([[2, 3, 9, 9],
       [9, 1, 9, 7],
       [3, 7, 9, 4]])

In [64]:
np.mean(arr3)

6.0

In [66]:
np.median(arr3)

7.0

In [67]:
np.std(arr3)

3.0276503540974917

In [68]:
np.var(arr3)

9.166666666666666

In [69]:
np.min(arr3)

1

In [70]:
np.max(arr3)

9